actions/image-partition: define ImagePath variable
The variable hasn't been defined yet so ends up producing
a build failure:

    actions/image_partition_action.go:371:2: undefined: ImagePath
    actions/image_partition_action.go:372:26: undefined: ImagePath
    actions/image_partition_action.go:384:34: undefined: ImagePath

Fix the syntax used to initialise this variable.

Fixes: a7afc01562bf ("actions/image-partition: Consistently use artifactdir")

Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>